options:
  auto-update: true
  breeding-cycle-duration: 40

nests:
  generate-while-growing-trees: true
  worlds:
    - worldnamehere
    - worldnamehere_nether
    - worldnamehere_the_end

discoveries:
  broadcast-first-discovery: true
