options:
  auto-update: true
  breeding-cycle-duration: 40

nests:
  tree-growth-generate-chance: 0.02
  worlds:
    - worldnamehere
    - worldnamehere_nether
    - worldnamehere_the_end

discoveries:
  broadcast-first-discovery: true
