name: SlimyBees
author: martinbrom
description: Forestry Bees Inspired Addon for Slimefun 4
main: cz.martinbrom.slimybees.SlimyBees
website: https://github.com/martinbrom/SlimyBees
version: ${project.version}
api-version: 1.15
depend:
  - Slimefun
