name: Pull Request Labels

on:
  pull_request:
    types:
      - opened

jobs:
  pr-labeler:

    name: Pull Request Labels
    runs-on: ubuntu-latest
    if: github.repository == 'martinbrom/SlimyBees'

    steps:
      - uses: baked-libs/pull-request-labels@v1.1
        id: labeller
        name: Apply labels based on branch
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          feature: '🎈 Feature'
          feat: '🎈 Feature'
          fix: '✨ Fix'
          chore: '🧹 Chore'

      - uses: thollander/actions-comment-pull-request@1.0.1
        name: Leave a comment about the applied label
        if: ${{ steps.labeller.outputs.applied != 0 }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Your Pull Request was automatically labelled as: "${{ steps.labeller.outputs.applied }}"
      - uses: thollander/actions-comment-pull-request@1.0.1
